###
GET http://localhost:3000/users/22 HTTP/1.1
content-type: application/json

###
GET http://localhost:3000/users/60567ce969b4b0840dcf67eb HTTP/1.1
content-type: application/json

###
GET http://localhost:3000/users/cell/9 HTTP/1.1
content-type: application/json

###
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "name":"Aliny",
    "cpf": "243423",
    "age": 22,
    "cell": 121212132
}

###
PATCH http://localhost:3000/users/60567d0469b4b0840dcf67ec HTTP/1.1
content-type: application/json

{
    "name":"Carlos"
}

###
DELETE  http://localhost:3000/users/60567d0469b4b0840dcf67ec HTTP/1.1
content-type: application/json